// Command generate compiles the supported OpenAPI request schemas into Go data.
// Unsupported constructs fail here rather than silently weakening validation.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"slices"
	"sort"
	"strings"

	"github.com/magichourhq/cli/internal/catalog"
)

type metadata struct {
	ID, Group, Name, Kind, Example string
	Files                          map[string]string
	Overrides                      map[string]struct {
		Flag     string `json:"flag"`
		Default  string `json:"default"`
		FileKind string `json:"file_kind"`
		Required bool   `json:"required"`
		MinItems int    `json:"min_items"`
	}
}

type schema struct {
	Type, Description                        string
	Properties                               map[string]json.RawMessage
	Required                                 []string
	Items                                    json.RawMessage
	Enum                                     []any
	Minimum, Maximum                         json.Number
	MinLength, MaxLength, MinItems, MaxItems int
	Deprecated                               bool
	MultipleOf                               json.Number
	Pattern, Format                          string
	Nullable                                 bool
}

func main() {
	specPath := flag.String("spec", "", "OpenAPI input")
	metaPath := flag.String("metadata", "", "CLI metadata input")
	outPath := flag.String("out", "", "Generated Go output")
	flag.Parse()
	if err := generate(*specPath, *metaPath, *outPath); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate(specPath, metaPath, outPath string) error {
	var spec struct {
		Paths map[string]map[string]struct {
			ID          string `json:"operationId"`
			Summary     string
			RequestBody struct {
				Content map[string]struct{ Schema json.RawMessage }
			}
		}
	}
	var metas []metadata
	for path, target := range map[string]any{specPath: &spec, metaPath: &metas} {
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if err := json.Unmarshal(data, target); err != nil {
			return fmt.Errorf("%s: %w", path, err)
		}
	}
	var out bytes.Buffer
	// New generation endpoints must get an explicit command name and file roles.
	selected := map[string]bool{}
	for _, m := range metas {
		if selected[m.ID] {
			return fmt.Errorf("duplicate operation %s", m.ID)
		}
		selected[m.ID] = true
	}
	for _, methods := range spec.Paths {
		if op, ok := methods["post"]; ok && op.ID != "videoAssets.generatePresignedUrl" && !selected[op.ID] {
			return fmt.Errorf("operation %s needs CLI metadata", op.ID)
		}
	}
	fmt.Fprintln(&out, "// Code generated by go generate; DO NOT EDIT.\n\npackage catalog\n\nvar Operations = []Operation{")
	seen := map[string]bool{}
	for _, m := range metas {
		key := m.Group + " " + m.Name
		if seen[key] {
			return fmt.Errorf("duplicate command %s", key)
		}
		seen[key] = true
		var matches int
		for path, methods := range spec.Paths {
			for method, op := range methods {
				if op.ID != m.ID {
					continue
				}
				matches++
				if method != "post" {
					return fmt.Errorf("%s: expected POST generation operation", m.ID)
				}
				fields, err := flatten(op.RequestBody.Content["application/json"].Schema, nil, true)
				if err != nil {
					return fmt.Errorf("%s: %w", m.ID, err)
				}
				rule, err := compile(op.RequestBody.Content["application/json"].Schema)
				if err != nil {
					return fmt.Errorf("%s: %w", m.ID, err)
				}
				used := map[string]bool{}
				flags := map[string]bool{}
				for i := range fields {
					f := &fields[i]
					p := strings.Join(f.Path, ".")
					if override, ok := m.Overrides[p]; ok {
						used[p] = true
						if override.Flag != "" {
							f.Flag = override.Flag
						}
						f.Default, f.FileKind = override.Default, override.FileKind
						f.Required = f.Required || override.Required
						f.MinItems = max(f.MinItems, override.MinItems)
					}
					if flags[f.Flag] || slices.Contains([]string{"help", "format", "dry-run", "output", "no-wait", "no-download", "timeout"}, f.Flag) {
						return fmt.Errorf("%s: flag collision --%s", m.ID, f.Flag)
					}
					flags[f.Flag] = true
					if f.FileKind != "" && (!validRole(f.FileKind) || (f.Type != "string" && f.Type != "array")) {
						return fmt.Errorf("%s: invalid file role or shape for --%s", m.ID, f.Flag)
					}
				}
				for p := range m.Overrides {
					if !used[p] {
						return fmt.Errorf("%s: stale override %s", m.ID, p)
					}
				}
				// Render typed literals; no OpenAPI parsing is needed in the CLI binary.
				fmt.Fprintf(&out, "{ID: %q, Group: %q, Name: %q, Kind: %q, Path: %q, Summary: %q, Example: %q,\nFields: []Field{\n", m.ID, m.Group, m.Name, m.Kind, path, op.Summary, m.Example)
				for _, field := range fields {
					literal := strings.TrimPrefix(fmt.Sprintf("%#v", field), "catalog.Field")
					fmt.Fprintf(&out, "%s,\n", literal)
				}
				fmt.Fprintln(&out, "},Schema:")
				writeRule(&out, rule)
				fmt.Fprintln(&out, ",Files: []FileInput{")
				for _, f := range fields {
					if f.FileKind == "" {
						continue
					}
					p := f.Path
					if f.Type == "array" {
						p = append(append([]string{}, p...), "*")
					}
					fmt.Fprintf(&out, "{Path:%#v,Kind:%q},\n", p, f.FileKind)
				}
				paths := make([]string, 0, len(m.Files))
				for p := range m.Files {
					paths = append(paths, p)
				}
				sort.Strings(paths)
				for _, p := range paths {
					if !validRole(m.Files[p]) {
						return fmt.Errorf("%s: invalid file role %s", m.ID, m.Files[p])
					}
					parts := strings.Split(p, ".")
					if !filePathExists(rule, parts) {
						return fmt.Errorf("%s: stale file path %s", m.ID, p)
					}
					fmt.Fprintf(&out, "{Path:%#v,Kind:%q},\n", parts, m.Files[p])
				}
				fmt.Fprintln(&out, "}},")
			}
		}
		if matches != 1 {
			return fmt.Errorf("%s: expected one operation, found %d", m.ID, matches)
		}
	}
	fmt.Fprintln(&out, "}")
	data, err := format.Source(out.Bytes())
	if err != nil {
		return err
	}
	return os.WriteFile(outPath, data, 0644)
}

func validRole(role string) bool {
	return slices.Contains([]string{"image", "video", "audio", "media", "video-or-gif"}, role)
}

func flatten(raw json.RawMessage, path []string, required bool) ([]catalog.Field, error) {
	var s schema
	if err := json.Unmarshal(raw, &s); err != nil {
		return nil, err
	}
	if s.Deprecated {
		return nil, nil
	}
	var keys map[string]json.RawMessage
	if err := json.Unmarshal(raw, &keys); err != nil {
		return nil, err
	}
	for key := range keys {
		if strings.HasPrefix(key, "x-") {
			continue
		}
		if !slices.Contains([]string{"type", "description", "properties", "required", "items", "enum", "minimum", "maximum", "minLength", "maxLength", "minItems", "maxItems", "deprecated", "example", "examples", "default", "title", "format", "nullable", "multipleOf", "pattern"}, key) {
			return nil, fmt.Errorf("%s: unsupported schema keyword %s", strings.Join(path, "."), key)
		}
	}
	if s.Type == "object" {
		var fields []catalog.Field
		names := make([]string, 0, len(s.Properties))
		for name := range s.Properties {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			children, err := flatten(s.Properties[name], append(append([]string{}, path...), name), required && slices.Contains(s.Required, name))
			if err != nil {
				return nil, err
			}
			fields = append(fields, children...)
		}
		return fields, nil
	}
	f := catalog.Field{Flag: strings.ReplaceAll(strings.Join(path, "-"), "_", "-"), Path: path, Type: s.Type, Help: strings.Split(s.Description, "\n")[0], Required: required, Minimum: string(s.Minimum), Maximum: string(s.Maximum), MinLength: s.MinLength, MaxLength: s.MaxLength, MinItems: s.MinItems, MaxItems: s.MaxItems}
	for _, v := range s.Enum {
		f.Enum = append(f.Enum, fmt.Sprint(v))
	}
	switch s.Type {
	case "string", "integer", "number", "boolean":
	case "array":
		var item schema
		if err := json.Unmarshal(s.Items, &item); err != nil {
			return nil, err
		}
		items, err := flatten(s.Items, path, false)
		if err != nil {
			return nil, err
		}
		if item.Type == "string" && len(items) == 1 && len(items[0].Enum) == 0 && len(s.Enum) == 0 {
			f.MinLength, f.MaxLength = items[0].MinLength, items[0].MaxLength
		} else {
			f.Type = "json"
		}
	default:
		return nil, fmt.Errorf("%s: unsupported type %q", f.Flag, s.Type)
	}
	return []catalog.Field{f}, nil
}

func compile(raw json.RawMessage) (catalog.Rule, error) {
	var s schema
	if err := json.Unmarshal(raw, &s); err != nil {
		return catalog.Rule{}, err
	}
	if s.Pattern != "" {
		if _, err := regexp.Compile(s.Pattern); err != nil {
			return catalog.Rule{}, err
		}
	}
	if !slices.Contains([]string{"", "float", "uri"}, s.Format) {
		return catalog.Rule{}, fmt.Errorf("unsupported format %s", s.Format)
	}
	r := catalog.Rule{Type: s.Type, Required: s.Required, Enum: s.Enum, Minimum: string(s.Minimum), Maximum: string(s.Maximum), MultipleOf: string(s.MultipleOf), MinLength: s.MinLength, MaxLength: s.MaxLength, MinItems: s.MinItems, MaxItems: s.MaxItems, Pattern: s.Pattern, Format: s.Format, Nullable: s.Nullable}
	if len(s.Items) > 0 {
		child, err := compile(s.Items)
		if err != nil {
			return r, err
		}
		r.Item = &child
	}
	if s.Type == "object" {
		r.Properties = map[string]catalog.Rule{}
		for name, raw := range s.Properties {
			var child schema
			if err := json.Unmarshal(raw, &child); err != nil {
				return r, err
			}
			if child.Deprecated {
				if slices.Contains(s.Required, name) {
					return r, fmt.Errorf("required deprecated field %s", name)
				}
				continue
			}
			c, err := compile(raw)
			if err != nil {
				return r, err
			}
			r.Properties[name] = c
		}
	}
	return r, nil
}

func writeRule(out *bytes.Buffer, r catalog.Rule) {
	var enum strings.Builder
	enum.WriteString("[]any{")
	for _, value := range r.Enum {
		if number, ok := value.(float64); ok {
			fmt.Fprintf(&enum, "float64(%v),", number)
		} else {
			fmt.Fprintf(&enum, "%#v,", value)
		}
	}
	enum.WriteString("}")
	fmt.Fprintf(out, "Rule{Type:%q,Required:%#v,Enum:%s,Minimum:%q,Maximum:%q,MultipleOf:%q,MinLength:%d,MaxLength:%d,MinItems:%d,MaxItems:%d,Pattern:%q,Format:%q,Nullable:%t,", r.Type, r.Required, enum.String(), r.Minimum, r.Maximum, r.MultipleOf, r.MinLength, r.MaxLength, r.MinItems, r.MaxItems, r.Pattern, r.Format, r.Nullable)
	if r.Item != nil {
		fmt.Fprint(out, "Item: &")
		writeRule(out, *r.Item)
		fmt.Fprint(out, ",")
	}
	if r.Properties != nil {
		fmt.Fprintln(out, "Properties: map[string]Rule{")
		keys := make([]string, 0, len(r.Properties))
		for k := range r.Properties {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			fmt.Fprintf(out, "%q:", k)
			writeRule(out, r.Properties[k])
			fmt.Fprintln(out, ",")
		}
		fmt.Fprint(out, "},")
	}
	fmt.Fprint(out, "}")
}

func filePathExists(r catalog.Rule, path []string) bool {
	if len(path) == 0 {
		return r.Type == "string"
	}
	if path[0] == "*" {
		return r.Item != nil && filePathExists(*r.Item, path[1:])
	}
	child, ok := r.Properties[path[0]]
	return ok && filePathExists(child, path[1:])
}
