// Command generate compiles the supported OpenAPI request schemas into Go data.
// Unsupported constructs fail here rather than silently weakening validation.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"slices"
	"sort"
	"strings"

	"github.com/magichourhq/magic-hour-cli/internal/catalog"
)

type metadata struct {
	ID, Group, Name, Kind, Example string
	Overrides                      map[string]struct {
		Flag     string `json:"flag"`
		Default  string `json:"default"`
		FileKind string `json:"file_kind"`
		Help     string `json:"help"`
		Required bool   `json:"required"`
		MinItems int    `json:"min_items"`
	}
}

type schema struct {
	Type, Description                        string
	Properties                               map[string]json.RawMessage
	Required                                 []string
	Items                                    json.RawMessage
	Enum                                     []any
	Minimum, Maximum                         json.Number
	MinLength, MaxLength, MinItems, MaxItems int
	Deprecated                               bool
}

func main() {
	specPath := flag.String("spec", "", "OpenAPI input")
	metaPath := flag.String("metadata", "", "CLI metadata input")
	outPath := flag.String("out", "", "Generated Go output")
	flag.Parse()
	if err := generate(*specPath, *metaPath, *outPath); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate(specPath, metaPath, outPath string) error {
	var spec struct {
		Paths map[string]map[string]struct {
			ID          string `json:"operationId"`
			Summary     string
			RequestBody struct {
				Content map[string]struct{ Schema json.RawMessage }
			}
		}
	}
	var metas []metadata
	for path, target := range map[string]any{specPath: &spec, metaPath: &metas} {
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if err := json.Unmarshal(data, target); err != nil {
			return fmt.Errorf("%s: %w", path, err)
		}
	}
	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by go generate; DO NOT EDIT.\n\npackage catalog\n\nvar Operations = []Operation{")
	seen := map[string]bool{}
	for _, m := range metas {
		key := m.Group + " " + m.Name
		if seen[key] {
			return fmt.Errorf("duplicate command %s", key)
		}
		seen[key] = true
		var matches int
		for path, methods := range spec.Paths {
			for method, op := range methods {
				if op.ID != m.ID {
					continue
				}
				matches++
				if method != "post" {
					return fmt.Errorf("%s: expected POST generation operation", m.ID)
				}
				fields, err := flatten(op.RequestBody.Content["application/json"].Schema, nil, true)
				if err != nil {
					return fmt.Errorf("%s: %w", m.ID, err)
				}
				used := map[string]bool{}
				flags := map[string]bool{}
				for i := range fields {
					f := &fields[i]
					p := strings.Join(f.Path, ".")
					if override, ok := m.Overrides[p]; ok {
						used[p] = true
						if override.Flag != "" {
							f.Flag = override.Flag
						}
						f.Default, f.FileKind = override.Default, override.FileKind
						if override.Help != "" {
							f.Help = override.Help
						}
						f.Required = f.Required || override.Required
						f.MinItems = max(f.MinItems, override.MinItems)
					}
					if flags[f.Flag] || slices.Contains([]string{"help", "format", "dry-run", "output", "no-wait", "no-download", "timeout"}, f.Flag) {
						return fmt.Errorf("%s: flag collision --%s", m.ID, f.Flag)
					}
					flags[f.Flag] = true
				}
				for p := range m.Overrides {
					if !used[p] {
						return fmt.Errorf("%s: stale override %s", m.ID, p)
					}
				}
				// Render typed literals; no OpenAPI parsing is needed in the CLI binary.
				fmt.Fprintf(&out, "{ID: %q, Group: %q, Name: %q, Kind: %q, Path: %q, Summary: %q, Example: %q,\nFields: []Field{\n", m.ID, m.Group, m.Name, m.Kind, path, op.Summary, m.Example)
				for _, field := range fields {
					literal := strings.TrimPrefix(fmt.Sprintf("%#v", field), "catalog.Field")
					fmt.Fprintf(&out, "%s,\n", literal)
				}
				fmt.Fprintln(&out, "}},")
			}
		}
		if matches != 1 {
			return fmt.Errorf("%s: expected one operation, found %d", m.ID, matches)
		}
	}
	fmt.Fprintln(&out, "}")
	data, err := format.Source(out.Bytes())
	if err != nil {
		return err
	}
	return os.WriteFile(outPath, data, 0644)
}

func flatten(raw json.RawMessage, path []string, required bool) ([]catalog.Field, error) {
	var s schema
	if err := json.Unmarshal(raw, &s); err != nil {
		return nil, err
	}
	if s.Deprecated {
		return nil, nil
	}
	var keys map[string]json.RawMessage
	if err := json.Unmarshal(raw, &keys); err != nil {
		return nil, err
	}
	for key := range keys {
		if strings.HasPrefix(key, "x-") {
			continue
		}
		if !slices.Contains([]string{"type", "description", "properties", "required", "items", "enum", "minimum", "maximum", "minLength", "maxLength", "minItems", "maxItems", "deprecated", "example", "examples", "default", "title"}, key) {
			return nil, fmt.Errorf("%s: unsupported schema keyword %s", strings.Join(path, "."), key)
		}
	}
	if s.Type == "object" {
		if len(path) > 0 && !required {
			return nil, fmt.Errorf("%s: optional objects need explicit handling", strings.Join(path, "."))
		}
		var fields []catalog.Field
		names := make([]string, 0, len(s.Properties))
		for name := range s.Properties {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			children, err := flatten(s.Properties[name], append(append([]string{}, path...), name), required && slices.Contains(s.Required, name))
			if err != nil {
				return nil, err
			}
			fields = append(fields, children...)
		}
		return fields, nil
	}
	f := catalog.Field{Flag: strings.ReplaceAll(strings.Join(path, "-"), "_", "-"), Path: path, Type: s.Type, Help: strings.Split(s.Description, "\n")[0], Required: required, Minimum: string(s.Minimum), Maximum: string(s.Maximum), MinLength: s.MinLength, MaxLength: s.MaxLength, MinItems: s.MinItems, MaxItems: s.MaxItems}
	for _, v := range s.Enum {
		f.Enum = append(f.Enum, fmt.Sprint(v))
	}
	switch s.Type {
	case "string", "integer", "number", "boolean":
	case "array":
		items, err := flatten(s.Items, path, false)
		if err != nil {
			return nil, err
		}
		if len(items) != 1 || items[0].Type != "string" || len(items[0].Enum) > 0 || len(s.Enum) > 0 {
			return nil, fmt.Errorf("%s: only arrays of strings are supported", f.Flag)
		}
		f.MinLength, f.MaxLength = items[0].MinLength, items[0].MaxLength
	default:
		return nil, fmt.Errorf("%s: unsupported type %q", f.Flag, s.Type)
	}
	return []catalog.Field{f}, nil
}
